### PR TITLE
Changes for new structure and 2020 updates

### LINKED ISSUE #7: Remove Jekyll-related metadata
There is metadata left-over that is specific to Jekyll. We should be fine to remove these. I believe they are "permalink" and "layout".

### LINKED ISSUE #42: Only provide bare minimum in data folder
Only have data for one indicator in data folder:

- CSV which complies with global DSD

### LINKED ISSUE #43: Upload indicator config yml file for each 2020 indicator

### LINKED ISSUE #44: Reconfigure default data/metadata inputs in data config file
Default inputs agreed are:

- CSV for data
- YML for metadata
- YML for indicator config

### PR DESCRIPTION
**Pull request by LucyGwilliamAdmin**
Fixes #7 
Fixes #42
Fixes #43 
Fixes #44

### CODE REVIEW

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I wasn't sure what to include in the [1-1-1.yml](meta/1-1-1.yml) metadata file. 

I tried to look at just the prose fields here but there seems to be overlap with the indicator-config yml files

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I tried a small tweak (I figured that users would not want changes to indicator config to affect the last-updated date) but that didn't work. I think the problem is just the empty metadata file. I believe it had any fields at all, it would complete without error.

Regarding what metadata fields to add - would it be a good time to do this?
1. Add the SDMX metadata concepts to this file in SDG Translations: https://github.com/open-sdg/sdg-translations/blob/1.4.0-dev/translations/en/metadata_fields.yml
2. Update the _prose.yml in this repo with these changes:
    1. Remove anything that is already in indicator config (with the exception of `reporting_status`, which needs to stay in _prose.yml)
    2. Remove anything that is Jekyll-related (like permalink, layout, etc.)
    3. Remove everything in the "national" scope
    4. Remove anything else that *should* be in indicator config, and then add it to indicator config (I think that "data_keywords" is the only example of this)
    5. Finally add all of the SDMX concepts as "national" scope
3. Start off 1.1.1 with example metadata using the SDMX concepts

**Comment by brockfanning** [comment]
For step 1, I put up this PR: https://github.com/open-sdg/sdg-translations/pull/208
For step 2, I can add a commit to this PR. (Also a correction, the "data_keywords" doesn't actually have any special function, so I think we can just remove it from the _prose.yml file here.)

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I also added a separate PR for your review, as an overhaul of the _prose.yml schema, to get it more metadata-only and set up for the SDMX concepts. https://github.com/open-sdg/open-sdg-data-starter/pull/46

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning thanks for putting that PR up and outlining the steps - that's really useful.

So for step 3. metadata file for 1.1.1 do we want all of the metadata fields from the new prose file? for national and global?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin It could be argued either way, but personally I'd say just national, with the idea being that countries will pull in global directly from the UNSD database. At this time UNSD doesn't yet have all indicators in their database, but maybe it will be done by the time 1.4.0 is released. In the meantime, the blurb on the global tab links to [here](https://unstats.un.org/sdgs/metadata/) which might be sufficient.

Also FYI, countries need to do either the main concepts only, or all the detail concepts, but not both the main and detail concepts. For example, they need to either do just [section 2](https://github.com/worldbank/sdg-metadata-convert/blob/master/lib/store/concepts.json#L83-L85), or [all of 2a, 2b, and 2c](https://github.com/worldbank/sdg-metadata-convert/blob/master/lib/store/concepts.json#L88-L100).

So for our starter repos we should choose an approach. It might be less intimidating to just fill in the main concepts. But it might also be reasonable to set a precedent by starting with all the detail concepts filled in.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Starting with the detailed concepts sounds fine to me. I'm wondering if UNSD may be published general metadata authoring advice soon, which might cover the difference between the main/detail concepts. Actually I misspoke earlier - countries are not "required" to fill out all the detail concepts - just as many as they can. With metadata it's just the more the better, I think. But to avoid duplicate work or confusion, it is important that they know that they don't have to fill in *both* the main *and* detail concepts. That might a note we can add to the updated Open SDG docs on metadata.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning do you think it would be better to provide just one file with the detailed concepts or two files (one with main, one with detailed) and then for the country to choose at the beginning and delete the file that they don't want to keep or do you think that would be making things too complicated?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin My inclination is to keep it simple by providing only one example, for now. I agree it would be good to find out what most countries are doing - my impression so far as that most are doing detail concepts. In all the metadata trainings I've been in, that has been the focus.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I've just added the detailed SDMX concepts to 1.1.1.yml - do you think there's anything we can add from translations - I was thinking we could do goal, target and indicator but when I just revisited the definitions I noticed they ask for number and name - what are your thoughts?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin My first thought is to create an "es" folder and another 1-1-1.yml file inside it, and then copy some/all content from the SDG Metadata project, which has translations of the global metadata for [English](https://github.com/worldbank/sdg-metadata/tree/master/translations-metadata/en) and [Spanish](https://github.com/worldbank/sdg-metadata/tree/master/translations-metadata/es).

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning no probs - I'll copy some of that over now - I shouldn't copy the html though right?

**Comment by LucyGwilliamAdmin** [comment]
Also I'm now wondering should we have for every field `: >-` after the field name instead of just `:`

I'm just thinking that it doesn't hurt for shorter field values follow `: >-` but could maybe get complicated having a mix?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin The HTML might be confusing to users, yeah. I think Markdown can be used, right? So maybe `## Foo` instead of `<h2>Foo</h2>`?

That seems reasonable about the `: >-`. Thinking longer term, if we do eventually start recommending the metadata config form, then that would handle it for the user. But I agree it might be better to have consistency now.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin My only comments are that I think we should remove the top margin on the first H2, and my personal preference would be to try without the italics.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning is the H2 margin an Open SDG thing?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Yes, any styling would need to be done in Open SDG. I've opened https://github.com/open-sdg/open-sdg/pull/1199 to try and deal with it. I had changed that PR to "draft" so we could think it through. but have just pushed an update for review.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Any concerns left here? I'm happy to approve if you're happy with it.

**Comment by LucyGwilliamAdmin** [comment]
Yeah @brockfanning , I think we're good to go on this one now

**Review by brockfanning — APPROVED** [review]

**Pull request merged**
