### PR TITLE
Update config.yml

### PR DESCRIPTION
**Pull request by LucyGwilliamAdmin**
Fixes https://github.com/open-sdg/sdg-build/issues/40

### CODE REVIEW

**Comment by brockfanning** [comment]
Hi @LucyGwilliamAdmin how are you populating all of those variables? (like $PROJECT, $ORGANIZATION, $CIRCLE_BRANCH, etc.)

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning they need to be added [here](https://circleci.com/gh/sdg-kyrgyzstan/open-sdg-data-starter/edit#env-vars)

Are they ok to be added there? Or should they be somewhere else?

**Comment by brockfanning** [comment]
You might try the approach taken with the deployment scripts ([example](https://github.com/open-sdg/open-sdg-data-starter/blob/develop/scripts/deploy/circleci/deploy_staging.sh)), where the variables are hardcoded into the scripts, with instructions to change them. Then the Circle config can just run that script, [like this](https://github.com/open-sdg/open-sdg-data-starter/blob/develop/.circleci/config.yml#L79). One upside of this approach is that you can add all the documentation right there in the script.

But one variable that should **not** be hardcoded into the script is CIRCLE_TOKEN. I think that needs to be kept secret, so should be done in the CircleCI dashboard like you're already doing. But there could be documentation in the script about how to create that token.

Also I think that the whole script should abort if CIRCLE_TOKEN does not exist. For example maybe something like:
```
if [[ -z "$CIRCLE_TOKEN" ]]; then
    echo "Skipping site build because CIRCLE_TOKEN is not set. See this script for instructions." 1>&2
    exit 0
fi
```

Also just a nitpick but you might make the variable names more specific to this usage. Like instead of PROJECT, something like SITE_REPO_NAME. And instead of ORGANIZATION, something like SITE_REPO_ORG? Likewise instead of CIRCLE_BRANCH, SITE_REPO_BRANCH, etc.?

**Comment by LucyGwilliamAdmin** [comment]
Thanks for your feedback, I will make those changes!

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I've changed the names of the environment variables (except CIRCLE_BRANCH since that's built-in to Circle) and also updated the docs with these changes in this [PR](https://github.com/open-sdg/open-sdg/pull/247)

**Comment by brockfanning** [comment]
Closing for now - see comments in https://github.com/open-sdg/open-sdg/pull/247

**Pull request closed without merging**
